# creation rules are evaluated sequentially, the first match wins
creation_rules:
        # upon creation of a file that matches the pattern *dev.yaml,
        # KMS set A is used
        # eGOV Internal ------------------------------------------------------------------------------------------------------------- #
        - path_regex: environments/abdeas-prod\-secrets\.yaml$
          kms: 'arn:aws:kms:ap-south-1:648721531140:key/da1d2aee-3ef5-4a80-86a3-478952dcc81b'

